### ISSUE TITLE
Option flag description spanning more than a single line

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#7] opened 2016-02-17 05:24 UTC
It would be nice to be able to have better control over the usage statement. In particular:
- [ ] Option flag descriptions spanning more than one line
-  ~~More control over general usage statement formatting and content~~
-  ~~Additional, non option text, such as usage examples etc.~~

~~It's possible that the last point is a non-issue, I need to examine the usage text parsing more carefully.~~

The first point will need some different usage statement parsing logic. It's possible that some sort of special line break character or string could be used, and then when the usage statement is parsed for options, consecutive lines containing the special character/string would be concatenated, but when the usage statement is printed a line break is inserted at that character. An easy candidate could be `\n` which when `echo`ed with `echo -e` would insert a line break. Thoughts?

~~Not sure what to do about the second point yet...~~

**Comment by kvz** [comment] 2016-02-17 08:25
Another thing I noticed is that we currently don't:

- [ ] Support dashed long options such as `--no-color`

I'll have to do more thinking about 1 & 2. I think `echo -e` might work yes. As for 3, maybe that's better left to the `help` function.

**Comment by zbeekman** [comment] 2016-02-17 13:52
oh, really? I can look into that.

I was thinking about the "delete key friendly" nature of the project, and now think that points 2 and 3 are invalid and can be dropped. We're making a template not a library/module. I'm going to cross out those issues.

**Comment by kvz** [comment] 2016-02-17 13:58
> oh, really? I can look into that.

That would be cool!

> I was thinking about the "delete key friendly" nature of the project, and now think that points 2 and 3 are invalid and can be dropped. We're making a template not a library/module. I'm going to cross out those issues.

I think I agree yes.

**Comment by zbeekman** [comment] 2016-02-20 02:46
> Another thing I noticed is that we currently don't:
> 
>  Support dashed long options such as --no-color

I have determined a fix for this issue. The problem relates to legal bash variable names. The character set of legal names is restricted to `[a-zA-Z_1-9]` with the further restriction that variable names may not start with a numeral. My proposed fix (PR should be incoming in the next 24 hrs) is to use a name mangling scheme. My proposal is to transform the variables corresponding to options with the following transformation:

```
sed -e 's#-#_#g' -e 's#^\([0-9]\)#_\1#'
```

The first regex transforms `-` long options to `_`. This will cause collisions, but I think this is an acceptable compromise. (`--no-color` and `--no_color` will collide...) The second regex prepends a leading underscore to the variable name corresponding to any short or long option starting with a numeral. (`-1` and `-_1` will collide)

Other than Bash4 associative arrays, I can't think of a better solution to the problem than my proposed "name mangling" approach.

Thoughts?

**Comment by zbeekman** [comment] 2016-02-20 04:37
I was mistaken about the issue of flags like `-1`. All indirect references using `eval` to create variable names dynamically start with some static text for the variable name. The only issue was the dashes in the long options. I could swear that I had done some testing indicating that options starting with numerals were an issue, but was not able to recreate my findings. Additionally, inspection of the code seems to indicate this is not an issue. PR submitted: #9

**Comment by zbeekman** [comment] 2016-03-17 04:06
So to circle back around to the original feature request:

> option descriptions spanning more than one line

I'm wondering what the best way to do this is. I have two ideas:

 1. Make indentation significant: We could parse a line from the short option through the beginning of the white space preceding the option description (after long options and `[arg]` if present) and note the column at which the description starts. Then when parsing the next line we could see if there is any text before that column, and if not make it part of the previous lines option definition.
 2. Just look at the next line and check for a short option definition. If the line does not have a short option definition consider it part of the previous option definition line.

Option 2 is much easier to implement.

```
# method 1
 -s --short-option-lengthened [arg] This is my description. Using method 1 I can break it
                                    across lines so long as the indentation matches up. Programming
                                    this in sed is going to be a royal PITA.
 -n --next-option ...

# method 2
-s --short-option-lengthended [arg] Method two of continuing across lines is much easier to implement
  and is indentation agnostic. Just don't start continued lines with a - character
 -n --next-option ...
```

**Comment by kvz** [comment] 2016-03-17 10:56
Alternatively we could allow people to add `\n` to their descriptions? Much uglier though I'd have to admit. Can't say I'm comfortable predicting which of the two other routes would be easier to implement. But I do agree this is a nice to have.

**Comment by gdevenyi** [comment] 2016-06-21 14:34
While I'm into this addition, I'm agnostic to the implementation, anything will work for me.

**Comment by mstreuhofer** [comment] 2016-11-09 22:36
can somebody explain to me what the issue is? I'm reading these comments for the 5th time and I  still don't get it. Method 1 is working already. It's the job of the user to align the __usage so it looks fine. How does b3bp need to know or understand anything about indentation or not?

maybe I don't understand the issue because it refers to a much older version of the code and it can be closed by now?

**Comment by zbeekman** [comment] 2016-11-10 02:27
You could always use a here doc---theres syntax to strip leading
indentation and also to keep it (<<- vs <<)

**Comment by zbeekman** [comment] 2016-11-10 12:22
Sorry, my last comment was made on mobile in a hurry without a full understanding of @mstreuhofer'S question.

I think the outstanding issue is that the usage statement parser expects one option/switch per line. The outstanding work is to allow the descriptions of any given flag/switch to cover multiple lines. I don't believe this has been implemented but I could be wrong. I hope this clarifies things.

**Closed** 2016-11-18 14:45 UTC

**Comment by zbeekman** [comment] 2016-11-18 14:47
Thanks for your contribution @mstreuhofer 🎉
